require("../common/index.js");
require("./index.css");
require("../common/nav-simple/index.js");
var store=require("../../util/store.js");
var userService=require("../../service/user-service.js");
//错误栏提示
var errorItem={
    show:function(errorMsg){
        $(".error-item").show().find(".err-msg").text(errorMsg);
    },
    hide:function(){
        $(".error-item").hide();
    }
}
var page={
    init:function(){
      this.bindEvent(); 
    },
    bindEvent:function(){
       var _this=this;
       //异步验证用户名是否存在
       $("#username").blur(function(){
           var username=$.trim($(this).val());
           if(!username){
               return;
           }
           userService.checkUsername(username,function(){
               errorItem.hide();
           },function(errorMsg){
               errorItem.show(errorMsg);
           })

       })
       //点击输入框就隐藏错误栏
       $(".user-content").click(function(){
           if(!$(".error-item").find("error-msg").val()==="用户名已存在!"){  
               errorItem.hide();
            }
       })
       //登陆按钮提交
       $("#submit").click(function(){
           _this.submit();
       });
       //按下回车，提交
       $(".user-content").keyup(function(e){
            if(e.keyCode===13){
                _this.submit();
            }
       });
    },
    //提交
    submit:function(){
        $(".user-content").click(function(){
                errorItem.hide();
        })
        var userRegister={
            username:$.trim($("#username").val()),
            password:$.trim($("#password").val()),
            passwordConfirm:$.trim($("#password-confirm").val()),
            phone:$.trim($("#phone").val()),
            email:$.trim($("#email").val()),
            question:$.trim($("#question").val()),
            answer:$.trim($("#answer").val())
        }
        if(!store.validate(userRegister.username,"require")){
            errorItem.show("请输入用户名！");
            return;
        };
        if(!store.validate(userRegister.password,"require")){
            errorItem.show("请输入密码！");
            return;
        };
        if(userRegister.password.length<6){
            errorItem.show("密码长度不能少于6位!");
            return;
        };
        if(userRegister.password!=userRegister.passwordConfirm){
            errorItem.show("两次输入的密码不一致！");
            return;
        };
        if(!store.validate(userRegister.phone,"phone")){
            errorItem.show("手机号格式不对！");
            return;
        };
        if(!store.validate(userRegister.email,"email")){
            errorItem.show("邮箱格式不对!");
            return;
        };
        if(!store.validate(userRegister.question,"require")){
            errorItem.show("请输入密码提示问题!");
            return;
        };
        if(!store.validate(userRegister.answer,"require")){
            errorItem.show("请输入问题答案！");
            return;
        }; 
        userService.register(userRegister,function(){
            window.location.href="./result.html?type=register";
        },function(errorMsg){
            errorItem.show(errorMsg);
        });
    },
};
$(function(){
    page.init();
}); 
